Soporte para descuentos adicionales
NeoRazorX/facturacion_base pull request #92
Opened 2017-08-21 22:22 UTC by shawe

- Añadido soporte para 3 descuentos adicionales en las líneas de los documentos.
- Añadido soporte para 5 descuentos nuevos en los totales de los documentos.
- Modificado los valores a almacenar para que no se guarden en la DB redondeados, si está acortado provoca que se acumule error que a su vez causa que no pase las validaciones, ahora las validaciones se pueden pasar con exactitud en los decimales.
- Cambiados algunos textos "factura" por "FS_FACTURA".
- Los errores en los que se indica que el valor no coincide, se ha añadido el valor con el que se compara.
- En las vistas se ha separado en otro html la parte referente a las líneas del documento.
- He aprovechado y he añadido los cambios que te pidió @dilmix (y que me confirmaste por Slack que te parecía bien) para facilitarte el uso de leer valores con jQuery, son varios atributos "data-*"

Los cambios los he hecho como me has indicado, porque al usar todos los decimales, ya da igual hacerlo a nivel de línea que de subtotal. Sino recuerdo mal en el único lugar que se hace a nivel de subtotal, es donde no queda otra y es en 1 o 2 validaciones (referente a lineasivafactcli sino recuerdo mal).

Cualquier cosa que veas dudosa o que prefieras que se cambie avisame y me pongo con ello, he generado datos con el FSDK, y no me ha dado ningún problema.

El problema que creo que puede haber, es que creo puede que dé falsos positivos con documentos anteriores, ya que ahora al tener más decimales, no acumula errores que sin los decimales adicionales si se ven.

2017-08-22 09:04 UTC, NeoRazorX requested changes

2017-08-22 09:04 UTC, NeoRazorX commented on model/core/albaran_cliente.php
>                  $this->hora = date('H:i:s', strtotime($a['hora']));
En la copia local ya tengo todos los modelos usando $data en lugar de $a, $l, etc.
Cambia $a por $data para simplificar el pull.

2017-08-22 09:04 UTC, NeoRazorX commented on model/core/linea_iva_factura_cliente.php
> +            // Como el IVA se ha calculado por línea para tener compatibilidad con AbanQ/Eneboo
Esto lo has deducido tú, pero no veo por qué. Las líneas de iva las utilizo para generar las líneas de los asientos, me simplifica trabajo ¿Por qué llenarlas con datos incompletos? ¿Porqué no poner el neto de verdad?

2017-08-22 09:04 UTC, NeoRazorX commented on view/ventas_albaran.html
> +      {loop="$lineas"}{if="$value->dtopor2!=0 || $value->dtopor3!=0 || $value->dtopor4!=0"}show = true;{break}{/if}{/loop}
Esta parte de código puede ir en nueva_venta.js

2017-08-22 09:17 UTC, shawe commented on model/core/albaran_cliente.php
>                  $this->hora = date('H:i:s', strtotime($a['hora']));
Entendido, voy a ello

2017-08-22 09:46 UTC, shawe commented on model/core/linea_iva_factura_cliente.php
> +            // Como el IVA se ha calculado por línea para tener compatibilidad con AbanQ/Eneboo
Si, lo he deducido (erróneamente) porque lo pregunté en Slack y no tuve respuesta (o si la tuve no la ví), por eso es un comentario que he dejado a postas.

Los campos que he puesto como netosindto y neto, deberían ser subtotales y base imponible (por lo menos de cara al usuario). Si aplico los descuentos de totales trasladandolo a las líneas, el subtotal es igual a la base imponible, y eso no es cierto, además que se refleja a nivel de línea una descuento en el total de línea, que no es real, porqué no le pertenece ahí.

El descuento no es a nivel de línea, es a nivel de subtotales del documento, y son cosas diferentes aunque puedan llegar a compararse como lo mismo, por eso a pesar de no saber el porqué lo quisiste así, lo hice así todo lo que pude o vi claro para no interferir (o que lo hicieran en la menor medida posible, como es el caso de los decimales adicionales) con los cálculos previos.

Tomando ejemplos como: http://www.facturae.gob.es/formato/Documents/EspanolFacturae3_0.pdf

Este documento es sobre el FacturaE que has implementado (posiblemente este en concreto sea antiguo) y en el constan diferenciados los "Descuentos/Cargos generales" como "Totales de factura" y el "Descuento" como "Líneas de detalle" páginas 2, y en las páginas 11, 12, 23 y 24 se ve este desglose, aunque no estén rellenando el campo descuento/cargo en el ejemplo.

Entiendo que en el caso de FacturaE, haciéndolo como me dices, se estaría "falseando" la información a rellenar, puesto que esta tabla contiene información que no se corresponde con la realidad de lo distribuido en los campos de descuentos.

2017-08-22 10:00 UTC, shawe commented on model/core/albaran_cliente.php
>                  $this->hora = date('H:i:s', strtotime($a['hora']));
Aplicado en facturacion_base y pedidos_y_presupuestos

2017-08-22 10:09 UTC, shawe commented on view/ventas_albaran.html
> +      {loop="$lineas"}{if="$value->dtopor2!=0 || $value->dtopor3!=0 || $value->dtopor4!=0"}show = true;{break}{/if}{/loop}
Hecho, he añadido <!--{$lineas=$fsc->documento_que_sea->get_lineas()}--> a las vistas que no lo tenían, y entonces si se puede para todos los casos con el bloque entero de código que añadí en cada vista.

2017-08-22 10:14 UTC, shawe commented on model/core/linea_iva_factura_cliente.php
> +            // Como el IVA se ha calculado por línea para tener compatibilidad con AbanQ/Eneboo
Si realmente se usa principalmente para los asientos, desconozco si hay algún inconveniente en ello, a priori sabiendo eso, me parece que no.

Añado el netosindto a esa tabla, y así se almacenan los 2 valores y de paso se puede añadir una comprobación adicional?

2017-08-22 10:40 UTC, NeoRazorX commented on model/core/linea_iva_factura_cliente.php
> +            // Como el IVA se ha calculado por línea para tener compatibilidad con AbanQ/Eneboo
De nuevo, esta tabla la utilizo para generar las líneas de los asientos. No necesito el neto sin descuento, ni los descuentos, ni nada que no sea el neto, impuesto y total (neto + impuesto).

2017-08-22 10:43 UTC, shawe commented on model/core/linea_iva_factura_cliente.php
> +            // Como el IVA se ha calculado por línea para tener compatibilidad con AbanQ/Eneboo
Voy al lío entonces

2017-08-22 10:45 UTC, NeoRazorX commented on model/core/linea_iva_factura_cliente.php
> +            // Como el IVA se ha calculado por línea para tener compatibilidad con AbanQ/Eneboo
Para dejarlo claro, necesito en lineasiva el desglose por impuestos. Para eso uso ese modelo.
Neto del impuesto, impuesto, total impuesto y total (neto + totalimpuesto).

2017-08-22 11:40 UTC, shawe commented on model/core/linea_iva_factura_cliente.php
> +            // Como el IVA se ha calculado por línea para tener compatibilidad con AbanQ/Eneboo
Ya está corregido, he generado 163 facturas a través de 675 albaranes, y no me ha dado ningún error en ninguna de las facturas al visualizarlas una a una.

2017-08-22 12:09 UTC, shawe commented
Creo que no lo dije, antes de aceptar finalmente todos estos cambios (aunque todavía falta aplicarlo a proveedores para dejarlo completo del todo, se puede hacer en PR distintos), hay que sacar unos mensajes de console.log de nueva_venta.js, que los puse por si querías probarlo en local antes de mergearlo, ya que creo que es posible que con los documentos hechos con anterioridad a estos cambios, aparezcan mensajes de que los importes no cuadran, cuando antes si lo hacían.

No estoy seguro de si aparecerán o no, porqué he ido vaciando la DB de pruebas, pero asumo que sí, ya que ahora al calcularse con todos los decimales, la vista obtendrá los resultados con más precisión de la que lo hacía antes.

Creo que una solución a esto sería añadir una comprobación como esta en https://github.com/shawe/facturacion_base/blob/master/model/core/linea_iva_factura_cliente.php#L153 , aunque no tengo claro el cómo exactamente para garantizarlo en todos los casos:

```
if(preg_match('/^[0-9]+\.[0-9]{2}$/', $li_neto)){
        // Comprobar con el redondeo
        $li_neto = round($li_neto, FS_NF0);
        $li_iva = round($li_iva, FS_NF0);
        $li_recargo = round($li_recargo, FS_NF0);

        // Podrían haber falsos positivos que antes no daban error
        // También podrían haber casos que anteriormente daban error y ahora el error sería levemente mayor
} else {
        // Comprobar sin el redondeo
}

```
Como $neto, $totaliva, $totalrecargo llegan calculados con todos los decimales, no podríamos añadirlo en el if, aunque si podríamos usar $fac->get($idfactura)->neto para comprobar si tiene 2 decimales del cálculo anterior almacenado y en dicho caso reemplazar los valores de $neto, $totaliva y $totalrecargo por los almacenados, para comparar en igualdad de condiciones de nuevo.

2017-08-29 17:50 UTC, NeoRazorX approved these changes

2017-08-29 18:03 UTC, NeoRazorX commented
Tras aplicar este pull, ya no deja añadir líneas a los albaranes de venta abiertos. Tanto añadir un artículo como una línea libre no produce resultados.

2017-08-31 09:19 UTC, NeoRazorX requested changes
Al editar albaranes de venta no permite añadir líneas. Haces clic pero no hace nada, ni devuelve error.

2017-08-31 09:22 UTC, shawe commented
@NeoRazorX arreglado ese error, cambié "lineas_albaran" por "lineas_doc" en alguna vista (tampoco en todas), pero no en el JS. Lo he cambiado por un termino más genérico, ya que no todo son albaranes, pero si son documentos.

Este cambio debe aplicarse como mínimo a los plugins "unidades_medida" de @joenilson, "servicios" de @pcrednet , "reservas" de @CruzeroGroup2, "haiti" de @joenilson, "editar_facturas" de @NeoRazorX, entre otros que puede que no tenga descargados, por eso dije como mínimo. Con un reemplazar masivo de "lineas_albaran" por "lineas_doc", omitiendo del reemplazo lo que sean funciones que contienen ese nombre, es suficiente, rápido y directo.

2017-08-31 14:58 UTC, shawe commented
El último commit he añadido lo que me has indicado, y lo he probado con editar_facturas para asegurarme, y funciona bien, el plugin de haiti con el que quería probarlo no sirve de prueba, porque reemplaza este mismo js.

2017-09-05 15:18 UTC, NeoRazorX approved these changes

2017-09-05 15:18 UTC, NeoRazorX commented
Más errores, al modificar un albarán de venta, añadir líneas y guardar, sale este error:
Notice: Undefined property: ventas_albaran::$presupuesto in /var/www/html/FS_2015/plugins/facturacion_base/controller/ventas_albaran.php on line 347

2017-09-06 08:15 UTC, shawe commented
He añadido los descuentos adicionales en nueva_venta, que lo dejé para cuando acabase de comprobar el resto y al final se me pasó, y hecho un par de correcciones menores en algunos HTML que me había comido un <tr>.

A menos que se encuentre algún bug adicional, diría que ahora si está completo para ventas.

Para compras preferiría hacerlo en una segunda fase, ya que lo que el cliente encargó era sólo para ventas, y en compras, ya lo iré añadiendo de mis ratos libres, o si se saca en una financiación colectiva, mejor que mejor para todos.

2017-09-07 21:39 UTC, merged