facturacion_base: Tarea 6225 para agregar funciones fs_generar_numero…
NeoRazorX/facturacion_base pull request #94
Opened 2017-08-29 18:25 UTC by joenilson

…2 y fs_documento_post_save

Archivos involucrados:
- compras_agrupar_albaranes.php
- compras_albaran.php
- compras_factura_devolucion.php
- nueva_compra.php
- nueva_venta.php
- tpv_recambios.php
- ventas_agrupar_albaranes.php
- ventas_albaran.php
- ventas_factura.php
- ventas_factura_devolucion.php
- functions.php

2017-08-31 16:47 UTC, NeoRazorX requested changes
Se necesitan estos cambios.

2017-08-31 16:47 UTC, NeoRazorX commented on functions.php
> +        $ok = false;
Si solamente devuelve true, se puede cambiar todo este código por un return true;
Fijate que haces $ok = true, pero ni haces return, ni tiene sentido esa comprobación para hacer simplemente $ok = true.

2017-08-31 16:47 UTC, NeoRazorX commented on functions.php
> +     * @return string
No hay ningún return en la función.

2017-08-31 16:47 UTC, NeoRazorX commented on functions.php
> +        if(empty($documento->$campo) and !empty($numero2)){
sustituye and por &&

2017-08-31 16:47 UTC, NeoRazorX commented on controller/nueva_compra.php
> -            $pedido->codagente = $this->agente->codagente;
¿Por qué desaparece codagente?

2017-08-31 17:00 UTC, joenilson commented on controller/nueva_compra.php
> -            $pedido->codagente = $this->agente->codagente;
No desaparece, al parecer le di un enter y luego le quite el enter y por eso identifica como -, pero luego lo pone como +

2017-08-31 17:00 UTC, joenilson commented on functions.php
> +        $ok = false;
corregido, procesando el pull-request

2017-08-31 17:00 UTC, joenilson commented on functions.php
> +        if(empty($documento->$campo) and !empty($numero2)){
corregido, procesando el pull-request

2017-08-31 17:01 UTC, joenilson commented on functions.php
> +     * @return string
corregido, procesando el pull-request

2017-09-01 14:42 UTC, NeoRazorX approved these changes

2017-09-07 21:39 UTC, merged