Relleno por defecto del campo orden, basado en el de creación
NeoRazorX/facturacion_base pull request #97
Opened 2017-09-14 18:52 UTC by shawe

Uso de show_numero en los valores de importes para extracciones a XLS y CSV

2017-09-15 08:34 UTC, NeoRazorX requested changes

2017-09-15 08:34 UTC, NeoRazorX commented on controller/informe_albaranes.php
> +                'neto' => $this->show_numero($doc->neto),
Recuerdo que daba problemas con muchas versiones de excel y libreoffice, que interpretaba los céntimos como miles.

2017-09-15 08:34 UTC, NeoRazorX commented on controller/informe_albaranes.php
> +                'neto' => $this->show_numero($doc->neto),
Lo mismo, al abrir con un libreoffice o excel, muchas veces interpretaba los céntimos como miles.

2017-09-15 08:34 UTC, NeoRazorX commented on controller/nueva_venta.php
> +                        $linea->orden = $i;
Todo este código ya esta cuadruplicado. Mejor crea una función nueva_linea_doc(&$documento, $iddoc = 'idfactura', $clas_name = 'linea_factura_cliente')

2017-09-18 18:07 UTC, shawe commented on controller/informe_albaranes.php
> +                'neto' => $this->show_numero($doc->neto),
Acabo de probar con el round de PHP, y me sigue funcionando bien (uso los valores por defecto).

Podría ser que lo que diera los problemas fuera que el show_numero hace uso del , y . configurado por el usuario con FS_NF1 y FS_NF2? Si fuera por eso, con el round no debería suceder nunca.

2017-09-18 18:28 UTC, shawe commented on controller/nueva_venta.php
> +                        $linea->orden = $i;
Me falta revisar esta parte, que no termino de entender a que te refieres.

2017-09-18 18:49 UTC, NeoRazorX commented
Olvida esto, no voy a aprobar más cambios. Ya me he pasado todo el fin de semana corrigiendo la última actualización.

2017-11-01 09:18 UTC, closed without merging